server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    password: $database13$
    url: jdbc:postgresql://localhost:5433/Drogeria
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
